#!/bin/bash

# This script installs bkarchive and bkrotate
echo "This script installs bkarchive and bkrotate to /usr/local/bin"

BKARCHIVEURL="https://raw.githubusercontent.com/ajzat34/backuptools/master/bkarchive.sh"
BKROTATEURL="https://raw.githubusercontent.com/ajzat34/backuptools/master/bkrotate.sh"
INSTALLTO="/usr/local/bin"

# Check for some stuff
if [ $(command -v curl) == "" ]; then
	echo "you need to install curl and/or add it to your path"
	exit 2
fi
if [ $(command -v whiptail) == "" ]; then
	echo "you need to install whiptail and/or add it to your path"
	exit 2
fi

if [ $(command -v bkarchive) != "" ]; then
  echo "you already have bkarchive installed $(command -v bkarchive)"
  exit 2
fi
if [ $(command -v bkrotate) != "" ]; then
  echo "you already have bkrotate installed $(command -v bkrotate)"
  exit 2
fi


echo "downloading $BKARCHIVEURL to $INSTALLTO/bkarchive"
curl "${BKARCHIVEURL}" -o "${INSTALLTO}/bkarchive"
if [ $? != 0 ]; then
  echo "failed!"
  exit 4
fi

echo "downloading $BKROTATEURL to $INSTALLTO/bkrotate"
curl "${BKROTATEURL}" -o "${INSTALLTO}/bkrotate"
if [ $? != 0 ]; then
  echo "failed!"
  exit 4
fi

exit

