#!/bin/bash

# This script installs bkarchive and bkrotate
echo "This script installs bkarchive and bkrotate to /usr/local/bin"
umask 775

if [ "$EUID" -ne 0 ]
  then echo "please run as root"
  exit
fi

# Check for some stuff
if [ $(command -v curl) == "" ]; then
	echo "you need to install curl and/or add it to your path"
	exit 2
fi
if [ $(command -v whiptail) == "" ]; then
	echo "you need to install whiptail and/or add it to your path"
	exit 2
fi

if [ $(command -v bkarchive) != "" ]; then
  echo "you already have bkarchive installed $(command -v bkarchive)"
  exit 2
fi
if [ $(command -v bkrotate) != "" ]; then
  echo "you already have bkrotate installed $(command -v bkrotate)"
  exit 2
fi


echo "downloading https://raw.githubusercontent.com/ajzat34/backuptools/master/bkarchive.sh to /usr/local/bin/bkarchive"
curl https://raw.githubusercontent.com/ajzat34/backuptools/master/bkarchive.sh -o /usr/local/bin/bkarchive"
if [ $? != 0 ]; then
  echo "failed!"
  exit 4
fi

echo "downloading https://raw.githubusercontent.com/ajzat34/backuptools/master/bkrotate.sh to /usr/local/bin/bkrotate"
curl https://raw.githubusercontent.com/ajzat34/backuptools/master/bkrotate.sh -o /usr/local/bin/bkrotate"
if [ $? != 0 ]; then
  echo "failed!"
  exit 4
fi

exit 0

