#!/bin/bash

# This script installs bkarchive and bkrotate
echo "This script installs bkarchive and bkrotate to /usr/local/bin"

BKARCHIVEURL="https://raw.githubusercontent.com/ajzat34/backuptools/master/bkarchive.sh"
BKROTATEURL="https://raw.githubusercontent.com/ajzat34/backuptools/master/bkrotate.sh"
INSTALLTO="/usr/local/bin"

unmask 0775

echo "downloading $BKARCHIVEURL to $INSTALLTO/bkarchive"
curl "${BKARCHIVEURL}" -o "${INSTALLTO}/bkarchive"
if [ $? != 0 ]; then
  echo "failed!"
  exit 4
fi

echo "downloading $BKROTATEURL to $INSTALLTO/bkrotate"
curl "${BKROTATEURL}" -o "${INSTALLTO}/bkrotate"
if [ $? != 0 ]; then
  echo "failed!"
  exit 4
fi

exit

